name: pose
description: Dart library for reading, writing, normalizing, augmenting, interpolating, transforming, normalizing and visualizing .pose files
version: 1.2.1
repository: https://github.com/bipinkrish/pose-dart
topics:
  - pose

environment:
  sdk: ^3.0.0

executables:
  pose_info:

dependencies:
  image: ^4.5.2
  tuple: ^2.0.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
